import React from 'react'

export default function Surrender() {
  return (
    <div className="space-y-8 px-2 sm:px-4 md:px-8 py-4 md:py-6">
      <div className="mb-2">
        <div className="text-[#1e3a8a] text-2xl md:text-3xl font-extrabold mb-1">■ 해약환급금 및 계약자적립액 예시</div>
        <div className="w-full h-1 bg-[#1e3a8a] mb-3" />
      </div>

      {/* 남자 표 */}
      <div className="text-sm text-gray-700">
        기준: 40세, 60세연금개시, 납입기간 10년납, 기본보험료 월 30만원, 월납, 글로벌멀티에셋자산배분형Ⅲ 100% 선택시
      </div>
      <div className="space-y-2">
        <div className="flex justify-between items-center text-sm text-gray-700">
          <span>[남자]</span>
          <span>(단위: 만원)</span>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-center text-xs md:text-sm min-w-[320px]">
            <colgroup>
              <col className="w-[6%]" />
              <col className="w-[7%]" />
              <col className="w-[7%]" />
              <col className="w-[7%]" />
              <col className="w-[7%]" />
              <col className="w-[7%]" />
              <col className="w-[7%]" />
              <col className="w-[7%]" />
              <col className="w-[7%]" />
              <col className="w-[7%]" />
              <col className="w-[7%]" />
              <col className="w-[7%]" />
              <col className="w-[7%]" />
              <col className="w-[7%]" />
            </colgroup>
            <thead>
              <tr className="bg-[#1e3a8a] text-white">
                <th className="border border-gray-300 p-1 text-xs" rowSpan={2}>구분</th>
                <th className="border border-gray-300 p-1 text-xs" rowSpan={2}>납입<br />보험료<br />(A)</th>
                <th className="border border-gray-300 p-1 text-xs" rowSpan={2}>특별계정<br />투입금액<br />누계</th>
                <th className="border border-gray-300 p-1 text-xs" colSpan={4}>투자수익률 -1% 가정<br />(순수익률 –3.65%)</th>
                <th className="border border-gray-300 p-1 text-xs" colSpan={4}>투자수익률 평균공시이율(2.50%)가정<br />(순수익률 -0.15%)</th>
                <th className="border border-gray-300 p-1 text-xs" colSpan={4}>투자수익률 평균공시이율×1.5(3.75%)가정<br />(순수익률 1.10%)</th>
              </tr>
              <tr className="bg-[#1e3a8a] text-white">
                <th className="border border-gray-300 p-1 text-xs">해약<br />환급금<br />(B)</th>
                <th className="border border-gray-300 p-1 text-xs">환급률<br />(B/A)</th>
                <th className="border border-gray-300 p-1 text-xs">계약자<br />적립액<br />(C)</th>
                <th className="border border-gray-300 p-1 text-xs">적립률<br />(C/A)</th>
                <th className="border border-gray-300 p-1 text-xs">해약<br />환급금<br />(B)</th>
                <th className="border border-gray-300 p-1 text-xs">환급률<br />(B/A)</th>
                <th className="border border-gray-300 p-1 text-xs">계약자<br />적립액<br />(C)</th>
                <th className="border border-gray-300 p-1 text-xs">적립률<br />(C/A)</th>
                <th className="border border-gray-300 p-1 text-xs">해약<br />환급금<br />(B)</th>
                <th className="border border-gray-300 p-1 text-xs">환급률<br />(B/A)</th>
                <th className="border border-gray-300 p-1 text-xs">계약자<br />적립액<br />(C)</th>
                <th className="border border-gray-300 p-1 text-xs">적립률<br />(C/A)</th>
              </tr>
            </thead>
            <tbody>
              <tr><td className="border border-gray-300 p-1 text-xs">3개월</td><td className="border border-gray-300 p-1 text-xs">90</td><td className="border border-gray-300 p-1 text-xs">83</td><td className="border border-gray-300 p-1 text-xs">0</td><td className="border border-gray-300 p-1 text-xs">0.0%</td><td className="border border-gray-300 p-1 text-xs">51</td><td className="border border-gray-300 p-1 text-xs">57.4%</td><td className="border border-gray-300 p-1 text-xs">0</td><td className="border border-gray-300 p-1 text-xs">0.0%</td><td className="border border-gray-300 p-1 text-xs">51</td><td className="border border-gray-300 p-1 text-xs">57.7%</td><td className="border border-gray-300 p-1 text-xs">0</td><td className="border border-gray-300 p-1 text-xs">0.0%</td><td className="border border-gray-300 p-1 text-xs">52</td><td className="border border-gray-300 p-1 text-xs">57.9%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">6개월</td><td className="border border-gray-300 p-1 text-xs">180</td><td className="border border-gray-300 p-1 text-xs">166</td><td className="border border-gray-300 p-1 text-xs">29</td><td className="border border-gray-300 p-1 text-xs">16.3%</td><td className="border border-gray-300 p-1 text-xs">103</td><td className="border border-gray-300 p-1 text-xs">57.3%</td><td className="border border-gray-300 p-1 text-xs">30</td><td className="border border-gray-300 p-1 text-xs">16.8%</td><td className="border border-gray-300 p-1 text-xs">104</td><td className="border border-gray-300 p-1 text-xs">57.9%</td><td className="border border-gray-300 p-1 text-xs">30</td><td className="border border-gray-300 p-1 text-xs">17.0%</td><td className="border border-gray-300 p-1 text-xs">104</td><td className="border border-gray-300 p-1 text-xs">58.1%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">9개월</td><td className="border border-gray-300 p-1 text-xs">270</td><td className="border border-gray-300 p-1 text-xs">249</td><td className="border border-gray-300 p-1 text-xs">83</td><td className="border border-gray-300 p-1 text-xs">30.8%</td><td className="border border-gray-300 p-1 text-xs">154</td><td className="border border-gray-300 p-1 text-xs">57.1%</td><td className="border border-gray-300 p-1 text-xs">85</td><td className="border border-gray-300 p-1 text-xs">31.7%</td><td className="border border-gray-300 p-1 text-xs">156</td><td className="border border-gray-300 p-1 text-xs">58.0%</td><td className="border border-gray-300 p-1 text-xs">86</td><td className="border border-gray-300 p-1 text-xs">32.0%</td><td className="border border-gray-300 p-1 text-xs">157</td><td className="border border-gray-300 p-1 text-xs">58.3%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">1년</td><td className="border border-gray-300 p-1 text-xs">360</td><td className="border border-gray-300 p-1 text-xs">333</td><td className="border border-gray-300 p-1 text-xs">136</td><td className="border border-gray-300 p-1 text-xs">38.1%</td><td className="border border-gray-300 p-1 text-xs">205</td><td className="border border-gray-300 p-1 text-xs">57.0%</td><td className="border border-gray-300 p-1 text-xs">140</td><td className="border border-gray-300 p-1 text-xs">39.1%</td><td className="border border-gray-300 p-1 text-xs">209</td><td className="border border-gray-300 p-1 text-xs">58.1%</td><td className="border border-gray-300 p-1 text-xs">142</td><td className="border border-gray-300 p-1 text-xs">39.5%</td><td className="border border-gray-300 p-1 text-xs">210</td><td className="border border-gray-300 p-1 text-xs">58.4%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">2년</td><td className="border border-gray-300 p-1 text-xs">720</td><td className="border border-gray-300 p-1 text-xs">666</td><td className="border border-gray-300 p-1 text-xs">349</td><td className="border border-gray-300 p-1 text-xs">48.5%</td><td className="border border-gray-300 p-1 text-xs">406</td><td className="border border-gray-300 p-1 text-xs">56.4%</td><td className="border border-gray-300 p-1 text-xs">364</td><td className="border border-gray-300 p-1 text-xs">50.6%</td><td className="border border-gray-300 p-1 text-xs">421</td><td className="border border-gray-300 p-1 text-xs">58.5%</td><td className="border border-gray-300 p-1 text-xs">369</td><td className="border border-gray-300 p-1 text-xs">51.4%</td><td className="border border-gray-300 p-1 text-xs">426</td><td className="border border-gray-300 p-1 text-xs">59.2%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">3년</td><td className="border border-gray-300 p-1 text-xs">1,080</td><td className="border border-gray-300 p-1 text-xs">999</td><td className="border border-gray-300 p-1 text-xs">557</td><td className="border border-gray-300 p-1 text-xs">51.7%</td><td className="border border-gray-300 p-1 text-xs">603</td><td className="border border-gray-300 p-1 text-xs">55.9%</td><td className="border border-gray-300 p-1 text-xs">590</td><td className="border border-gray-300 p-1 text-xs">54.7%</td><td className="border border-gray-300 p-1 text-xs">636</td><td className="border border-gray-300 p-1 text-xs">58.9%</td><td className="border border-gray-300 p-1 text-xs">603</td><td className="border border-gray-300 p-1 text-xs">55.8%</td><td className="border border-gray-300 p-1 text-xs">648</td><td className="border border-gray-300 p-1 text-xs">60.1%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">4년</td><td className="border border-gray-300 p-1 text-xs">1,440</td><td className="border border-gray-300 p-1 text-xs">1,332</td><td className="border border-gray-300 p-1 text-xs">762</td><td className="border border-gray-300 p-1 text-xs">52.9%</td><td className="border border-gray-300 p-1 text-xs">796</td><td className="border border-gray-300 p-1 text-xs">55.3%</td><td className="border border-gray-300 p-1 text-xs">820</td><td className="border border-gray-300 p-1 text-xs">57.0%</td><td className="border border-gray-300 p-1 text-xs">854</td><td className="border border-gray-300 p-1 text-xs">59.4%</td><td className="border border-gray-300 p-1 text-xs">842</td><td className="border border-gray-300 p-1 text-xs">58.5%</td><td className="border border-gray-300 p-1 text-xs">876</td><td className="border border-gray-300 p-1 text-xs">60.9%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">5년</td><td className="border border-gray-300 p-1 text-xs">1,800</td><td className="border border-gray-300 p-1 text-xs">1,666</td><td className="border border-gray-300 p-1 text-xs">963</td><td className="border border-gray-300 p-1 text-xs">53.5%</td><td className="border border-gray-300 p-1 text-xs">985</td><td className="border border-gray-300 p-1 text-xs">54.8%</td><td className="border border-gray-300 p-1 text-xs">1,053</td><td className="border border-gray-300 p-1 text-xs">58.5%</td><td className="border border-gray-300 p-1 text-xs">1,076</td><td className="border border-gray-300 p-1 text-xs">59.8%</td><td className="border border-gray-300 p-1 text-xs">1,088</td><td className="border border-gray-300 p-1 text-xs">60.5%</td><td className="border border-gray-300 p-1 text-xs">1,110</td><td className="border border-gray-300 p-1 text-xs">61.7%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">6년</td><td className="border border-gray-300 p-1 text-xs">2,160</td><td className="border border-gray-300 p-1 text-xs">2,002</td><td className="border border-gray-300 p-1 text-xs">1,163</td><td className="border border-gray-300 p-1 text-xs">53.9%</td><td className="border border-gray-300 p-1 text-xs">1,174</td><td className="border border-gray-300 p-1 text-xs">54.4%</td><td className="border border-gray-300 p-1 text-xs">1,293</td><td className="border border-gray-300 p-1 text-xs">59.9%</td><td className="border border-gray-300 p-1 text-xs">1,305</td><td className="border border-gray-300 p-1 text-xs">60.4%</td><td className="border border-gray-300 p-1 text-xs">1,343</td><td className="border border-gray-300 p-1 text-xs">62.2%</td><td className="border border-gray-300 p-1 text-xs">1,355</td><td className="border border-gray-300 p-1 text-xs">62.7%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">7년</td><td className="border border-gray-300 p-1 text-xs">2,520</td><td className="border border-gray-300 p-1 text-xs">2,339</td><td className="border border-gray-300 p-1 text-xs">1,360</td><td className="border border-gray-300 p-1 text-xs">54.0%</td><td className="border border-gray-300 p-1 text-xs">1,360</td><td className="border border-gray-300 p-1 text-xs">54.0%</td><td className="border border-gray-300 p-1 text-xs">1,537</td><td className="border border-gray-300 p-1 text-xs">61.0%</td><td className="border border-gray-300 p-1 text-xs">1,537</td><td className="border border-gray-300 p-1 text-xs">61.0%</td><td className="border border-gray-300 p-1 text-xs">1,605</td><td className="border border-gray-300 p-1 text-xs">63.7%</td><td className="border border-gray-300 p-1 text-xs">1,605</td><td className="border border-gray-300 p-1 text-xs">63.7%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">8년</td><td className="border border-gray-300 p-1 text-xs">2,880</td><td className="border border-gray-300 p-1 text-xs">2,676</td><td className="border border-gray-300 p-1 text-xs">1,541</td><td className="border border-gray-300 p-1 text-xs">53.5%</td><td className="border border-gray-300 p-1 text-xs">1,541</td><td className="border border-gray-300 p-1 text-xs">53.5%</td><td className="border border-gray-300 p-1 text-xs">1,772</td><td className="border border-gray-300 p-1 text-xs">61.5%</td><td className="border border-gray-300 p-1 text-xs">1,772</td><td className="border border-gray-300 p-1 text-xs">61.5%</td><td className="border border-gray-300 p-1 text-xs">1,863</td><td className="border border-gray-300 p-1 text-xs">64.7%</td><td className="border border-gray-300 p-1 text-xs">1,863</td><td className="border border-gray-300 p-1 text-xs">64.7%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">9년</td><td className="border border-gray-300 p-1 text-xs">3,240</td><td className="border border-gray-300 p-1 text-xs">3,013</td><td className="border border-gray-300 p-1 text-xs">1,720</td><td className="border border-gray-300 p-1 text-xs">53.1%</td><td className="border border-gray-300 p-1 text-xs">1,720</td><td className="border border-gray-300 p-1 text-xs">53.1%</td><td className="border border-gray-300 p-1 text-xs">2,011</td><td className="border border-gray-300 p-1 text-xs">62.1%</td><td className="border border-gray-300 p-1 text-xs">2,011</td><td className="border border-gray-300 p-1 text-xs">62.1%</td><td className="border border-gray-300 p-1 text-xs">2,128</td><td className="border border-gray-300 p-1 text-xs">65.7%</td><td className="border border-gray-300 p-1 text-xs">2,128</td><td className="border border-gray-300 p-1 text-xs">65.7%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">10년</td><td className="border border-gray-300 p-1 text-xs">3,600</td><td className="border border-gray-300 p-1 text-xs">3,350</td><td className="border border-gray-300 p-1 text-xs">1,894</td><td className="border border-gray-300 p-1 text-xs">52.6%</td><td className="border border-gray-300 p-1 text-xs">1,894</td><td className="border border-gray-300 p-1 text-xs">52.6%</td><td className="border border-gray-300 p-1 text-xs">2,253</td><td className="border border-gray-300 p-1 text-xs">62.6%</td><td className="border border-gray-300 p-1 text-xs">2,253</td><td className="border border-gray-300 p-1 text-xs">62.6%</td><td className="border border-gray-300 p-1 text-xs">2,400</td><td className="border border-gray-300 p-1 text-xs">66.7%</td><td className="border border-gray-300 p-1 text-xs">2,400</td><td className="border border-gray-300 p-1 text-xs">66.7%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">20년</td><td className="border border-gray-300 p-1 text-xs">3,600</td><td className="border border-gray-300 p-1 text-xs">3,350</td><td className="border border-gray-300 p-1 text-xs">924</td><td className="border border-gray-300 p-1 text-xs">25.7%</td><td className="border border-gray-300 p-1 text-xs">924</td><td className="border border-gray-300 p-1 text-xs">25.7%</td><td className="border border-gray-300 p-1 text-xs">1,827</td><td className="border border-gray-300 p-1 text-xs">50.8%</td><td className="border border-gray-300 p-1 text-xs">1,827</td><td className="border border-gray-300 p-1 text-xs">50.8%</td><td className="border border-gray-300 p-1 text-xs">2,289</td><td className="border border-gray-300 p-1 text-xs">63.6%</td><td className="border border-gray-300 p-1 text-xs">2,289</td><td className="border border-gray-300 p-1 text-xs">63.6%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">25년</td><td className="border border-gray-300 p-1 text-xs">3,600</td><td className="border border-gray-300 p-1 text-xs">3,350</td><td className="border border-gray-300 p-1 text-xs">0</td><td className="border border-gray-300 p-1 text-xs">0.0%</td><td className="border border-gray-300 p-1 text-xs">0</td><td className="border border-gray-300 p-1 text-xs">0.0%</td><td className="border border-gray-300 p-1 text-xs">0</td><td className="border border-gray-300 p-1 text-xs">0.0%</td><td className="border border-gray-300 p-1 text-xs">0</td><td className="border border-gray-300 p-1 text-xs">0.0%</td><td className="border border-gray-300 p-1 text-xs">313</td><td className="border border-gray-300 p-1 text-xs">8.7%</td><td className="border border-gray-300 p-1 text-xs">312</td><td className="border border-gray-300 p-1 text-xs">8.7%</td></tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* 여자 표 */}
      <div className="space-y-2 mt-8">
        <div className="flex justify-between items-center text-sm text-gray-700">
          <span>[여자]</span>
          <span>(단위: 만원)</span>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-center text-xs md:text-sm min-w-[320px]">
            <colgroup>
              <col className="w-[6%]" />
              <col className="w-[6%]" />
              <col className="w-[6%]" />
              <col className="w-[6%]" />
              <col className="w-[6%]" />
              <col className="w-[6%]" />
              <col className="w-[6%]" />
              <col className="w-[6%]" />
              <col className="w-[6%]" />
              <col className="w-[6%]" />
              <col className="w-[6%]" />
              <col className="w-[6%]" />
              <col className="w-[6%]" />
              <col className="w-[6%]" />
            </colgroup>
            <thead>
              <tr className="bg-[#1e3a8a] text-white">
                <th className="border border-gray-300 p-1 text-xs" rowSpan={2}>구분</th>
                <th className="border border-gray-300 p-1 text-xs" rowSpan={2}>납입<br />보험료<br />(A)</th>
                <th className="border border-gray-300 p-1 text-xs" rowSpan={2}>특별계정<br />투입금액<br />누계</th>
                <th className="border border-gray-300 p-1 text-xs" colSpan={4}>투자수익률 -1% 가정<br />(순수익률 –3.65%)</th>
                <th className="border border-gray-300 p-1 text-xs" colSpan={4}>투자수익률 평균공시이율(2.50%)가정<br />(순수익률 -0.15%)</th>
                <th className="border border-gray-300 p-1 text-xs" colSpan={4}>투자수익률 평균공시이율×1.5(3.75%)가정<br />(순수익률 1.10%)</th>
              </tr>
              <tr className="bg-[#1e3a8a] text-white">
                <th className="border border-gray-300 p-1 text-xs">해약<br />환급금<br />(B)</th>
                <th className="border border-gray-300 p-1 text-xs">환급률<br />(B/A)</th>
                <th className="border border-gray-300 p-1 text-xs">계약자<br />적립액<br />(C)</th>
                <th className="border border-gray-300 p-1 text-xs">적립률<br />(C/A)</th>
                <th className="border border-gray-300 p-1 text-xs">해약<br />환급금<br />(B)</th>
                <th className="border border-gray-300 p-1 text-xs">환급률<br />(B/A)</th>
                <th className="border border-gray-300 p-1 text-xs">계약자<br />적립액<br />(C)</th>
                <th className="border border-gray-300 p-1 text-xs">적립률<br />(C/A)</th>
                <th className="border border-gray-300 p-1 text-xs">해약<br />환급금<br />(B)</th>
                <th className="border border-gray-300 p-1 text-xs">환급률<br />(B/A)</th>
                <th className="border border-gray-300 p-1 text-xs">계약자<br />적립액<br />(C)</th>
                <th className="border border-gray-300 p-1 text-xs">적립률<br />(C/A)</th>
              </tr>
            </thead>
            <tbody>
              <tr><td className="border border-gray-300 p-1 text-xs">3개월</td><td className="border border-gray-300 p-1 text-xs">90</td><td className="border border-gray-300 p-1 text-xs">83</td><td className="border border-gray-300 p-1 text-xs">0</td><td className="border border-gray-300 p-1 text-xs">0.0%</td><td className="border border-gray-300 p-1 text-xs">51</td><td className="border border-gray-300 p-1 text-xs">57.4%</td><td className="border border-gray-300 p-1 text-xs">0</td><td className="border border-gray-300 p-1 text-xs">0.0%</td><td className="border border-gray-300 p-1 text-xs">51</td><td className="border border-gray-300 p-1 text-xs">57.7%</td><td className="border border-gray-300 p-1 text-xs">0</td><td className="border border-gray-300 p-1 text-xs">0.0%</td><td className="border border-gray-300 p-1 text-xs">52</td><td className="border border-gray-300 p-1 text-xs">57.9%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">6개월</td><td className="border border-gray-300 p-1 text-xs">180</td><td className="border border-gray-300 p-1 text-xs">166</td><td className="border border-gray-300 p-1 text-xs">29</td><td className="border border-gray-300 p-1 text-xs">16.3%</td><td className="border border-gray-300 p-1 text-xs">103</td><td className="border border-gray-300 p-1 text-xs">57.3%</td><td className="border border-gray-300 p-1 text-xs">30</td><td className="border border-gray-300 p-1 text-xs">16.8%</td><td className="border border-gray-300 p-1 text-xs">104</td><td className="border border-gray-300 p-1 text-xs">57.9%</td><td className="border border-gray-300 p-1 text-xs">30</td><td className="border border-gray-300 p-1 text-xs">17.0%</td><td className="border border-gray-300 p-1 text-xs">104</td><td className="border border-gray-300 p-1 text-xs">58.1%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">9개월</td><td className="border border-gray-300 p-1 text-xs">270</td><td className="border border-gray-300 p-1 text-xs">249</td><td className="border border-gray-300 p-1 text-xs">83</td><td className="border border-gray-300 p-1 text-xs">30.8%</td><td className="border border-gray-300 p-1 text-xs">154</td><td className="border border-gray-300 p-1 text-xs">57.1%</td><td className="border border-gray-300 p-1 text-xs">85</td><td className="border border-gray-300 p-1 text-xs">31.7%</td><td className="border border-gray-300 p-1 text-xs">156</td><td className="border border-gray-300 p-1 text-xs">58.0%</td><td className="border border-gray-300 p-1 text-xs">86</td><td className="border border-gray-300 p-1 text-xs">32.0%</td><td className="border border-gray-300 p-1 text-xs">157</td><td className="border border-gray-300 p-1 text-xs">58.3%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">1년</td><td className="border border-gray-300 p-1 text-xs">360</td><td className="border border-gray-300 p-1 text-xs">333</td><td className="border border-gray-300 p-1 text-xs">137</td><td className="border border-gray-300 p-1 text-xs">38.1%</td><td className="border border-gray-300 p-1 text-xs">205</td><td className="border border-gray-300 p-1 text-xs">57.0%</td><td className="border border-gray-300 p-1 text-xs">140</td><td className="border border-gray-300 p-1 text-xs">39.1%</td><td className="border border-gray-300 p-1 text-xs">209</td><td className="border border-gray-300 p-1 text-xs">58.1%</td><td className="border border-gray-300 p-1 text-xs">142</td><td className="border border-gray-300 p-1 text-xs">39.5%</td><td className="border border-gray-300 p-1 text-xs">210</td><td className="border border-gray-300 p-1 text-xs">58.5%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">2년</td><td className="border border-gray-300 p-1 text-xs">720</td><td className="border border-gray-300 p-1 text-xs">666</td><td className="border border-gray-300 p-1 text-xs">349</td><td className="border border-gray-300 p-1 text-xs">48.5%</td><td className="border border-gray-300 p-1 text-xs">406</td><td className="border border-gray-300 p-1 text-xs">56.4%</td><td className="border border-gray-300 p-1 text-xs">364</td><td className="border border-gray-300 p-1 text-xs">50.6%</td><td className="border border-gray-300 p-1 text-xs">421</td><td className="border border-gray-300 p-1 text-xs">58.5%</td><td className="border border-gray-300 p-1 text-xs">369</td><td className="border border-gray-300 p-1 text-xs">51.4%</td><td className="border border-gray-300 p-1 text-xs">426</td><td className="border border-gray-300 p-1 text-xs">59.2%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">3년</td><td className="border border-gray-300 p-1 text-xs">1,080</td><td className="border border-gray-300 p-1 text-xs">999</td><td className="border border-gray-300 p-1 text-xs">557</td><td className="border border-gray-300 p-1 text-xs">51.7%</td><td className="border border-gray-300 p-1 text-xs">603</td><td className="border border-gray-300 p-1 text-xs">55.9%</td><td className="border border-gray-300 p-1 text-xs">591</td><td className="border border-gray-300 p-1 text-xs">54.7%</td><td className="border border-gray-300 p-1 text-xs">636</td><td className="border border-gray-300 p-1 text-xs">58.9%</td><td className="border border-gray-300 p-1 text-xs">603</td><td className="border border-gray-300 p-1 text-xs">55.8%</td><td className="border border-gray-300 p-1 text-xs">648</td><td className="border border-gray-300 p-1 text-xs">60.1%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">4년</td><td className="border border-gray-300 p-1 text-xs">1,440</td><td className="border border-gray-300 p-1 text-xs">1,332</td><td className="border border-gray-300 p-1 text-xs">762</td><td className="border border-gray-300 p-1 text-xs">52.9%</td><td className="border border-gray-300 p-1 text-xs">796</td><td className="border border-gray-300 p-1 text-xs">55.3%</td><td className="border border-gray-300 p-1 text-xs">820</td><td className="border border-gray-300 p-1 text-xs">57.0%</td><td className="border border-gray-300 p-1 text-xs">854</td><td className="border border-gray-300 p-1 text-xs">59.4%</td><td className="border border-gray-300 p-1 text-xs">842</td><td className="border border-gray-300 p-1 text-xs">58.5%</td><td className="border border-gray-300 p-1 text-xs">876</td><td className="border border-gray-300 p-1 text-xs">60.9%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">5년</td><td className="border border-gray-300 p-1 text-xs">1,800</td><td className="border border-gray-300 p-1 text-xs">1,666</td><td className="border border-gray-300 p-1 text-xs">963</td><td className="border border-gray-300 p-1 text-xs">53.5%</td><td className="border border-gray-300 p-1 text-xs">985</td><td className="border border-gray-300 p-1 text-xs">54.8%</td><td className="border border-gray-300 p-1 text-xs">1,053</td><td className="border border-gray-300 p-1 text-xs">58.6%</td><td className="border border-gray-300 p-1 text-xs">1,076</td><td className="border border-gray-300 p-1 text-xs">59.8%</td><td className="border border-gray-300 p-1 text-xs">1,088</td><td className="border border-gray-300 p-1 text-xs">60.5%</td><td className="border border-gray-300 p-1 text-xs">1,110</td><td className="border border-gray-300 p-1 text-xs">61.7%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">6년</td><td className="border border-gray-300 p-1 text-xs">2,160</td><td className="border border-gray-300 p-1 text-xs">2,002</td><td className="border border-gray-300 p-1 text-xs">1,163</td><td className="border border-gray-300 p-1 text-xs">53.9%</td><td className="border border-gray-300 p-1 text-xs">1,174</td><td className="border border-gray-300 p-1 text-xs">54.4%</td><td className="border border-gray-300 p-1 text-xs">1,293</td><td className="border border-gray-300 p-1 text-xs">59.9%</td><td className="border border-gray-300 p-1 text-xs">1,305</td><td className="border border-gray-300 p-1 text-xs">60.4%</td><td className="border border-gray-300 p-1 text-xs">1,343</td><td className="border border-gray-300 p-1 text-xs">62.2%</td><td className="border border-gray-300 p-1 text-xs">1,355</td><td className="border border-gray-300 p-1 text-xs">62.7%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">7년</td><td className="border border-gray-300 p-1 text-xs">2,520</td><td className="border border-gray-300 p-1 text-xs">2,339</td><td className="border border-gray-300 p-1 text-xs">1,360</td><td className="border border-gray-300 p-1 text-xs">54.0%</td><td className="border border-gray-300 p-1 text-xs">1,360</td><td className="border border-gray-300 p-1 text-xs">54.0%</td><td className="border border-gray-300 p-1 text-xs">1,537</td><td className="border border-gray-300 p-1 text-xs">61.0%</td><td className="border border-gray-300 p-1 text-xs">1,537</td><td className="border border-gray-300 p-1 text-xs">61.0%</td><td className="border border-gray-300 p-1 text-xs">1,606</td><td className="border border-gray-300 p-1 text-xs">63.7%</td><td className="border border-gray-300 p-1 text-xs">1,606</td><td className="border border-gray-300 p-1 text-xs">63.7%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">8년</td><td className="border border-gray-300 p-1 text-xs">2,880</td><td className="border border-gray-300 p-1 text-xs">2,676</td><td className="border border-gray-300 p-1 text-xs">1,542</td><td className="border border-gray-300 p-1 text-xs">53.5%</td><td className="border border-gray-300 p-1 text-xs">1,542</td><td className="border border-gray-300 p-1 text-xs">53.5%</td><td className="border border-gray-300 p-1 text-xs">1,772</td><td className="border border-gray-300 p-1 text-xs">61.5%</td><td className="border border-gray-300 p-1 text-xs">1,772</td><td className="border border-gray-300 p-1 text-xs">61.5%</td><td className="border border-gray-300 p-1 text-xs">1,863</td><td className="border border-gray-300 p-1 text-xs">64.7%</td><td className="border border-gray-300 p-1 text-xs">1,863</td><td className="border border-gray-300 p-1 text-xs">64.7%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">9년</td><td className="border border-gray-300 p-1 text-xs">3,240</td><td className="border border-gray-300 p-1 text-xs">3,013</td><td className="border border-gray-300 p-1 text-xs">1,720</td><td className="border border-gray-300 p-1 text-xs">53.1%</td><td className="border border-gray-300 p-1 text-xs">1,720</td><td className="border border-gray-300 p-1 text-xs">53.1%</td><td className="border border-gray-300 p-1 text-xs">2,011</td><td className="border border-gray-300 p-1 text-xs">62.1%</td><td className="border border-gray-300 p-1 text-xs">2,011</td><td className="border border-gray-300 p-1 text-xs">62.1%</td><td className="border border-gray-300 p-1 text-xs">2,128</td><td className="border border-gray-300 p-1 text-xs">65.7%</td><td className="border border-gray-300 p-1 text-xs">2,128</td><td className="border border-gray-300 p-1 text-xs">65.7%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">10년</td><td className="border border-gray-300 p-1 text-xs">3,600</td><td className="border border-gray-300 p-1 text-xs">3,350</td><td className="border border-gray-300 p-1 text-xs">1,894</td><td className="border border-gray-300 p-1 text-xs">52.6%</td><td className="border border-gray-300 p-1 text-xs">1,894</td><td className="border border-gray-300 p-1 text-xs">52.6%</td><td className="border border-gray-300 p-1 text-xs">2,253</td><td className="border border-gray-300 p-1 text-xs">62.6%</td><td className="border border-gray-300 p-1 text-xs">2,253</td><td className="border border-gray-300 p-1 text-xs">62.6%</td><td className="border border-gray-300 p-1 text-xs">2,400</td><td className="border border-gray-300 p-1 text-xs">66.7%</td><td className="border border-gray-300 p-1 text-xs">2,400</td><td className="border border-gray-300 p-1 text-xs">66.7%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">20년</td><td className="border border-gray-300 p-1 text-xs">3,600</td><td className="border border-gray-300 p-1 text-xs">3,350</td><td className="border border-gray-300 p-1 text-xs">924</td><td className="border border-gray-300 p-1 text-xs">25.7%</td><td className="border border-gray-300 p-1 text-xs">924</td><td className="border border-gray-300 p-1 text-xs">25.7%</td><td className="border border-gray-300 p-1 text-xs">1,827</td><td className="border border-gray-300 p-1 text-xs">50.8%</td><td className="border border-gray-300 p-1 text-xs">1,827</td><td className="border border-gray-300 p-1 text-xs">50.8%</td><td className="border border-gray-300 p-1 text-xs">2,290</td><td className="border border-gray-300 p-1 text-xs">63.6%</td><td className="border border-gray-300 p-1 text-xs">2,290</td><td className="border border-gray-300 p-1 text-xs">63.6%</td></tr>
              <tr><td className="border border-gray-300 p-1 text-xs">25년</td><td className="border border-gray-300 p-1 text-xs">3,600</td><td className="border border-gray-300 p-1 text-xs">3,350</td><td className="border border-gray-300 p-1 text-xs">0</td><td className="border border-gray-300 p-1 text-xs">0.0%</td><td className="border border-gray-300 p-1 text-xs">0</td><td className="border border-gray-300 p-1 text-xs">0.0%</td><td className="border border-gray-300 p-1 text-xs">0</td><td className="border border-gray-300 p-1 text-xs">0.0%</td><td className="border border-gray-300 p-1 text-xs">0</td><td className="border border-gray-300 p-1 text-xs">0.0%</td><td className="border border-gray-300 p-1 text-xs">399</td><td className="border border-gray-300 p-1 text-xs">11.1%</td><td className="border border-gray-300 p-1 text-xs">398</td><td className="border border-gray-300 p-1 text-xs">11.1%</td></tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* 주석 */}
      <div className="text-xs md:text-sm text-gray-800 space-y-2 mt-6">
        <p>주1) 이 보험계약은 납입한 보험료 중 사업비(계약체결비용, 계약관리비용(유지관련비용, 기타비용))를 차감한 후 특별계정으로 투입·운용되고, 특별계정(펀드)의 투자수익률이 반영된 특별계정 계약자적립액에서 위험보험료 및 보증비용 등이 차감됩니다. 상기 순수익률은 보증비용 등이 차감된 후의 수익률입니다.</p>
        <p>주2) 특별계정(펀드) 투자수익률은 펀드의 기준가격의 변동으로 계산되며, 특별계정운용보수, 증권거래비용 및 기타비용은 매일 차감되어 기준가격에 반영되어 있습니다.</p>
        <p>주3) 해약환급금은 특별계정 수익률에 따라 매일 변동하며, 중도해지시 특별계정 계약자적립액에서 미상각신계약비(해약공제액)를 차감하므로 해약환급금은 납입보험료보다 적거나 없을 수도 있습니다.</p>
        <p>주4) 해약환급금에는 최저보증이 없어 원금손실이 발생할 수 있으며, 그 손실은 모두 계약자에게 귀속됩니다.</p>
        <p>주5) 상기 환급률은 투자수익률이 경과기간동안 일정하게 유지된다고 가정하였을 때 계약자가 납입한 보험료 대비 해약환급금의 비율입니다.</p>
        <p>주6) 상기 예시된 금액 및 환급률 등이 미래의 수익을 보장하는 것은 아닙니다.</p>
        <p>주7) 상기예시금액의 투자수익률은 -1%, 감독규정 제1-2조 제13호에 따른 2026년도 평균공시이율 2.50% 및 동 이율의 1.5배인 3.75%를 기준으로 계산한 금액입니다.</p>
        <p>주8) 평균공시이율은 감독원장이 정하는 바에 따라 산정한 전체보험회사 공시이율의 평균으로, 전년도 8월말 기준 직전 12개월간 보험회사 평균 공시이율입니다.</p>
      </div>
    </div>
  )
}
